import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/styles/globals.css';

const nexa = localFont({
  src: [
    {
      path: '../fonts/nexa-800.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../fonts/nexa-900.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-nexa',
});

const nexaText = localFont({
  src: [
    {
      path: '../fonts/nexa-text-400.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/nexa-text-600.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../fonts/nexa-text-700.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../fonts/nexa-text-900.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-nexa-text',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nexa.variable} ${nexaText.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
